// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: InvestiGO

#include "../ui.h"

void ui_HomePage_screen_init(void)
{
    ui_HomePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomePage, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomePageBeginButton = lv_btn_create(ui_HomePage);
    lv_obj_set_width(ui_HomePageBeginButton, 600);
    lv_obj_set_height(ui_HomePageBeginButton, 80);
    lv_obj_set_x(ui_HomePageBeginButton, 0);
    lv_obj_set_y(ui_HomePageBeginButton, 103);
    lv_obj_set_align(ui_HomePageBeginButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomePageBeginButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomePageBeginButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomePageBeginButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomePageBeginButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelAutorise = lv_label_create(ui_HomePageBeginButton);
    lv_obj_set_width(ui_labelAutorise, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelAutorise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelAutorise, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelAutorise, "Begin");
    lv_obj_set_style_text_font(ui_labelAutorise, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_HomePage);
    lv_obj_set_width(ui_Panel1, 459);
    lv_obj_set_height(ui_Panel1, 62);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -142);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -41);
    lv_obj_set_y(ui_Label2, -142);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Investi");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x002AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 77);
    lv_obj_set_y(ui_Label3, -141);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Go");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xF9FE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -70);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Let your journey begin here");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomePageBeginButton, ui_event_HomePageBeginButton, LV_EVENT_ALL, NULL);
	if(nfcTask != NULL)
	{
		vTaskSuspend(nfcTask);
		nfcTask = NULL;
	}
}
