// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: InvestiGO

#include "../ui.h"

void ui_LogInChoose_screen_init(void)
{
    ui_LogInChoose = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LogInChoose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LogInChoose, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogInChoose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LogInChoose, lv_color_hex(0x36FF00), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogInChoose, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LoginChooseLabel = lv_label_create(ui_LogInChoose);
    lv_obj_set_width(ui_LoginChooseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoginChooseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LoginChooseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoginChooseLabel, "Please, scan your card");
    lv_obj_set_style_text_color(ui_LoginChooseLabel, lv_color_hex(0x1A0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoginChooseLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LoginChooseLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogInScreenCancelButton = lv_btn_create(ui_LogInChoose);
    lv_obj_set_width(ui_LogInScreenCancelButton, 200);
    lv_obj_set_height(ui_LogInScreenCancelButton, 65);
    lv_obj_set_x(ui_LogInScreenCancelButton, -281);
    lv_obj_set_y(ui_LogInScreenCancelButton, 197);
    lv_obj_set_align(ui_LogInScreenCancelButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogInScreenCancelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LogInScreenCancelButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LogInScreenCancelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LogInScreenCancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CancelButtonLabel2 = lv_label_create(ui_LogInScreenCancelButton);
    lv_obj_set_width(ui_CancelButtonLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CancelButtonLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CancelButtonLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CancelButtonLabel2, "Cancel");
    lv_obj_set_style_text_color(ui_CancelButtonLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CancelButtonLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CancelButtonLabel2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LogInScreenCancelButton, ui_event_LogInScreenCancelButton, LV_EVENT_ALL, NULL);

}
