// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: InvestiGO

#include "../ui.h"

void ui_MoneyDelegateScreen_screen_init(void)
{
    ui_MoneyDelegateScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MoneyDelegateScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MoneyDelegateScreen, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MoneyDelegateScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoneyDelegateScreenHeaderLabel = lv_label_create(ui_MoneyDelegateScreen);
    lv_obj_set_width(ui_MoneyDelegateScreenHeaderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MoneyDelegateScreenHeaderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MoneyDelegateScreenHeaderLabel, 0);
    lv_obj_set_y(ui_MoneyDelegateScreenHeaderLabel, -165);
    lv_obj_set_align(ui_MoneyDelegateScreenHeaderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoneyDelegateScreenHeaderLabel, "Enter amount to ___:");
    lv_obj_set_style_text_font(ui_MoneyDelegateScreenHeaderLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoneyDelegateScreenTextArea = lv_textarea_create(ui_MoneyDelegateScreen);
    lv_obj_set_width(ui_MoneyDelegateScreenTextArea, 679);
    lv_obj_set_height(ui_MoneyDelegateScreenTextArea, 70);
    lv_obj_set_x(ui_MoneyDelegateScreenTextArea, 0);
    lv_obj_set_y(ui_MoneyDelegateScreenTextArea, -70);
    lv_obj_set_align(ui_MoneyDelegateScreenTextArea, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MoneyDelegateScreenTextArea,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_MoneyDelegateScreenTextArea, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoneyDelegateScreenKeyboard = lv_keyboard_create(ui_MoneyDelegateScreen);
    lv_keyboard_set_mode(ui_MoneyDelegateScreenKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_MoneyDelegateScreenKeyboard, 797);
    lv_obj_set_height(ui_MoneyDelegateScreenKeyboard, 245);
    lv_obj_set_x(ui_MoneyDelegateScreenKeyboard, 1);
    lv_obj_set_y(ui_MoneyDelegateScreenKeyboard, 113);
    lv_obj_set_align(ui_MoneyDelegateScreenKeyboard, LV_ALIGN_CENTER);

    lv_keyboard_set_textarea(ui_MoneyDelegateScreenKeyboard, ui_RegisterScreenNameInputArea);
    
    ui_MoneyDelegateScreenCancelButton = lv_btn_create(ui_MoneyDelegateScreen);
    lv_obj_set_width(ui_MoneyDelegateScreenCancelButton, 88);
    lv_obj_set_height(ui_MoneyDelegateScreenCancelButton, 32);
    lv_obj_set_x(ui_MoneyDelegateScreenCancelButton, -346);
    lv_obj_set_y(ui_MoneyDelegateScreenCancelButton, -216);
    lv_obj_set_align(ui_MoneyDelegateScreenCancelButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MoneyDelegateScreenCancelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MoneyDelegateScreenCancelButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MoneyDelegateScreenCancelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MoneyDelegateScreenCancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_MoneyDelegateScreenCancelButtonLabel = lv_label_create(ui_MoneyDelegateScreenCancelButton);
    lv_obj_set_width(ui_MoneyDelegateScreenCancelButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MoneyDelegateScreenCancelButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MoneyDelegateScreenCancelButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoneyDelegateScreenCancelButtonLabel, "Cancel");
    lv_obj_set_style_text_color(ui_MoneyDelegateScreenCancelButtonLabel, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MoneyDelegateScreenCancelButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    lv_obj_add_event_cb(ui_MoneyDelegateScreenCancelButton, ui_event_MoneyDelegateScreenCancelButton, LV_EVENT_ALL, NULL);

}
