// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: InvestiGO

#include "../ui.h"
void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenHeaderLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_MainScreenHeaderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainScreenHeaderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainScreenHeaderLabel, 0);
    lv_obj_set_y(ui_MainScreenHeaderLabel, -191);
    lv_obj_set_align(ui_MainScreenHeaderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainScreenHeaderLabel, "Welcome, PLACEHOLDER!");
    lv_obj_set_style_text_color(ui_MainScreenHeaderLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainScreenHeaderLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainScreenHeaderLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenInvestButton = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_MainScreenInvestButton, 179);
    lv_obj_set_height(ui_MainScreenInvestButton, 50);
    lv_obj_set_x(ui_MainScreenInvestButton, -300);
    lv_obj_set_y(ui_MainScreenInvestButton, 32);
    lv_obj_set_align(ui_MainScreenInvestButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainScreenInvestButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MainScreenInvestButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreenInvestButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenInvestButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenInvestButtonLabel = lv_label_create(ui_MainScreenInvestButton);
    lv_obj_set_width(ui_MainScreenInvestButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainScreenInvestButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MainScreenInvestButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainScreenInvestButtonLabel, "Invest");
    lv_obj_set_style_text_font(ui_MainScreenInvestButtonLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenBalanceLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_MainScreenBalanceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainScreenBalanceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainScreenBalanceLabel, 0);
    lv_obj_set_y(ui_MainScreenBalanceLabel, -127);
    lv_obj_set_align(ui_MainScreenBalanceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainScreenBalanceLabel, "Your balance: 999$");
    lv_obj_set_style_text_font(ui_MainScreenBalanceLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenDepositButton = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_MainScreenDepositButton, 179);
    lv_obj_set_height(ui_MainScreenDepositButton, 50);
    lv_obj_set_x(ui_MainScreenDepositButton, -300);
    lv_obj_set_y(ui_MainScreenDepositButton, 90);
    lv_obj_set_align(ui_MainScreenDepositButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainScreenDepositButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MainScreenDepositButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreenDepositButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenDepositButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenDepositButtonLabel = lv_label_create(ui_MainScreenDepositButton);
    lv_obj_set_width(ui_MainScreenDepositButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainScreenDepositButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MainScreenDepositButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainScreenDepositButtonLabel, "Deposit");
    lv_obj_set_style_text_font(ui_MainScreenDepositButtonLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenWithdrawButton = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_MainScreenWithdrawButton, 179);
    lv_obj_set_height(ui_MainScreenWithdrawButton, 50);
    lv_obj_set_x(ui_MainScreenWithdrawButton, -298);
    lv_obj_set_y(ui_MainScreenWithdrawButton, 149);
    lv_obj_set_align(ui_MainScreenWithdrawButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainScreenWithdrawButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MainScreenWithdrawButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreenWithdrawButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenWithdrawButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenWithdrawButtonLabel = lv_label_create(ui_MainScreenWithdrawButton);
    lv_obj_set_width(ui_MainScreenWithdrawButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainScreenWithdrawButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MainScreenWithdrawButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainScreenWithdrawButtonLabel, "Withdraw");
    lv_obj_set_style_text_font(ui_MainScreenWithdrawButtonLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	table = lv_table_create(ui_MainScreen);
    lv_obj_set_size(table, 250, 150);
    lv_obj_center(table);
	
	lv_obj_set_width(table, 543);
    lv_obj_set_height(table, 294);
    lv_obj_set_x(table, 97);
    lv_obj_set_y(table, 78);
    lv_obj_set_align(table, LV_ALIGN_CENTER);
    lv_table_set_col_width(table, 0, 350);
    // Заповнюємо таблицю
    //lv_table_set_cell_value(table, 0, 0, "Item 1");
    //lv_table_set_cell_value(table, 1, 0, "Item 2");
   // lv_table_set_cell_value(table, 2, 0, "Item 3");

    // Додаємо кнопки в другий стовпець
    
	
	
	/*
    ui_MainScreenTabView = lv_tabview_create(ui_MainScreen, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_MainScreenTabView, 543);
    lv_obj_set_height(ui_MainScreenTabView, 294);
    lv_obj_set_x(ui_MainScreenTabView, 97);
    lv_obj_set_y(ui_MainScreenTabView, 78);
    lv_obj_set_align(ui_MainScreenTabView, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainScreenTabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

     ui_TabPage1 = lv_tabview_add_tab(ui_MainScreenTabView, "Assets");
	
	lv_obj_t * label1 = lv_label_create(ui_TabPage1);
    lv_label_set_text(label1, "Welcome to Tab 1");
    lv_obj_align(label1, LV_ALIGN_CENTER, 0, 0);

    // Додаємо кнопку до вкладки 2
    lv_obj_t * btn = lv_btn_create(ui_TabPage1);
    lv_obj_align(btn, LV_ALIGN_CENTER, 0, 0);
    lv_obj_t * label2 = lv_label_create(btn);
    lv_label_set_text(label2, "Click Me!");

    // Додаємо текстове поле до вкладки 3
    lv_obj_t * textarea = lv_textarea_create(ui_TabPage1);
    lv_obj_set_size(textarea, 150, 50);
    lv_textarea_set_text(textarea, "Enter text here...");
    */
	
    ui_MainScreenLogoutButton = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_MainScreenLogoutButton, 179);
    lv_obj_set_height(ui_MainScreenLogoutButton, 50);
    lv_obj_set_x(ui_MainScreenLogoutButton, -299);
    lv_obj_set_y(ui_MainScreenLogoutButton, 205);
    lv_obj_set_align(ui_MainScreenLogoutButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainScreenLogoutButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MainScreenLogoutButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreenLogoutButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreenLogoutButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainScreenLogoutButtonLabel = lv_label_create(ui_MainScreenLogoutButton);
    lv_obj_set_width(ui_MainScreenLogoutButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainScreenLogoutButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MainScreenLogoutButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainScreenLogoutButtonLabel, "Log Out");
    lv_obj_set_style_text_font(ui_MainScreenLogoutButtonLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	lv_obj_add_event_cb(ui_MainScreenInvestButton, ui_event_MainScreenInvestButton, LV_EVENT_ALL, NULL);
	lv_obj_add_event_cb(ui_MainScreenDepositButton, ui_event_MainScreenDepositButton, LV_EVENT_ALL, NULL);
	lv_obj_add_event_cb(ui_MainScreenWithdrawButton, ui_event_MainScreenWithdrawButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainScreenLogoutButton, ui_event_MainScreenLogoutButton, LV_EVENT_ALL, NULL);
	
	
}
