// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: InvestiGO

#include "../ui.h"

void ui_RegisterScreen_screen_init(void)
{
    ui_RegisterScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RegisterScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RegisterScreen, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RegisterScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RegisterScreenLabel = lv_label_create(ui_RegisterScreen);
    lv_obj_set_width(ui_RegisterScreenLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RegisterScreenLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RegisterScreenLabel, 0);
    lv_obj_set_y(ui_RegisterScreenLabel, -164);
    lv_obj_set_align(ui_RegisterScreenLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RegisterScreenLabel, "What is your name?");
    lv_obj_set_style_text_font(ui_RegisterScreenLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RegisterScreenNameInputArea = lv_textarea_create(ui_RegisterScreen);
    lv_obj_set_width(ui_RegisterScreenNameInputArea, 679);
    lv_obj_set_height(ui_RegisterScreenNameInputArea, 70);
    lv_obj_set_x(ui_RegisterScreenNameInputArea, 0);
    lv_obj_set_y(ui_RegisterScreenNameInputArea, -70);
    lv_obj_set_align(ui_RegisterScreenNameInputArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_RegisterScreenNameInputArea, "Bob");
    lv_obj_clear_flag(ui_RegisterScreenNameInputArea,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_RegisterScreenNameInputArea, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RegisterScreenKeyboard = lv_keyboard_create(ui_RegisterScreen);
    lv_obj_set_width(ui_RegisterScreenKeyboard, 799);
    lv_obj_set_height(ui_RegisterScreenKeyboard, 219);
    lv_obj_set_x(ui_RegisterScreenKeyboard, -1);
    lv_obj_set_y(ui_RegisterScreenKeyboard, 130);
    lv_obj_set_align(ui_RegisterScreenKeyboard, LV_ALIGN_CENTER);

    ui_RegisterScreenCancelButton = lv_btn_create(ui_RegisterScreen);
    lv_obj_set_width(ui_RegisterScreenCancelButton, 88);
    lv_obj_set_height(ui_RegisterScreenCancelButton, 32);
    lv_obj_set_x(ui_RegisterScreenCancelButton, -346);
    lv_obj_set_y(ui_RegisterScreenCancelButton, -216);
    lv_obj_set_align(ui_RegisterScreenCancelButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RegisterScreenCancelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RegisterScreenCancelButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RegisterScreenCancelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RegisterScreenCancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RegisterScreenCancelButtonLabel = lv_label_create(ui_RegisterScreenCancelButton);
    lv_obj_set_width(ui_RegisterScreenCancelButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RegisterScreenCancelButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RegisterScreenCancelButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RegisterScreenCancelButtonLabel, "Cancel");
    lv_obj_set_style_text_color(ui_RegisterScreenCancelButtonLabel, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RegisterScreenCancelButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_RegisterScreenKeyboard, ui_RegisterScreenNameInputArea);
    lv_obj_add_event_cb(ui_RegisterScreenKeyboard, ui_event_RegisterScreenKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RegisterScreenCancelButton, ui_event_RegisterScreenCancelButton, LV_EVENT_ALL, NULL);

}
