// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: InvestiGO

#include "../ui.h"

void ui_SuccessScreen_screen_init(void)
{
    ui_SuccessScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SuccessScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SuccessScreen, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SuccessScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_SuccessScreen);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Success!");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SuccessScreenButton = lv_btn_create(ui_SuccessScreen);
    lv_obj_set_width(ui_SuccessScreenButton, 364);
    lv_obj_set_height(ui_SuccessScreenButton, 61);
    lv_obj_set_x(ui_SuccessScreenButton, -3);
    lv_obj_set_y(ui_SuccessScreenButton, 194);
    lv_obj_set_align(ui_SuccessScreenButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SuccessScreenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SuccessScreenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SuccessScreenButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SuccessScreenButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SuccessScreenButtonLabel = lv_label_create(ui_SuccessScreenButton);
    lv_obj_set_width(ui_SuccessScreenButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SuccessScreenButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SuccessScreenButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SuccessScreenButtonLabel, "Back");
    lv_obj_set_style_text_font(ui_SuccessScreenButtonLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SuccessScreenButton, ui_event_SuccessScreenButton, LV_EVENT_ALL, NULL);

}
