// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: InvestiGO

#include <stdio.h>
#include "ui.h"
#include "ui_helpers.h"
#include "database.c"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "widgets/lv_label.h"

#include <read_nfc.c>

///////////////////// VARIABLES ////////////////////

bool isInvest = false;
bool isDeposit = false;
bool isWithdraw = false;

// SCREEN: ui_HomePage
void ui_HomePage_screen_init(void);
lv_obj_t * ui_HomePage;
void ui_event_HomePageBeginButton(lv_event_t * e);
lv_obj_t * ui_HomePageBeginButton;
lv_obj_t * ui_labelAutorise;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_MainScreenHeaderLabel;
lv_obj_t * ui_MainScreenInvestButton;
lv_obj_t * ui_MainScreenInvestButtonLabel;
lv_obj_t * ui_MainScreenBalanceLabel;
lv_obj_t * ui_MainScreenDepositButton;
lv_obj_t * ui_MainScreenDepositButtonLabel;
lv_obj_t * ui_MainScreenWithdrawButton;
lv_obj_t * ui_MainScreenWithdrawButtonLabel;
lv_obj_t * ui_MainScreenTabView;
lv_obj_t * ui_TabPage1;
lv_obj_t * table;
void ui_event_MainScreenLogoutButton(lv_event_t * e);
lv_obj_t * ui_MainScreenLogoutButton;
lv_obj_t * ui_MainScreenLogoutButtonLabel;
// CUSTOM VARIABLES

// SCREEN: ui_LogInChoose
void ui_LogInChoose_screen_init(void);
lv_obj_t * ui_LogInChoose;
lv_obj_t * ui_LoginChooseLabel;
void ui_event_LogInScreenCancelButton(lv_event_t * e);
lv_obj_t * ui_LogInScreenCancelButton;
lv_obj_t * ui_CancelButtonLabel2;
// CUSTOM VARIABLES

// SCREEN: ui_RegisterScreen
void ui_RegisterScreen_screen_init(void);
lv_obj_t * ui_RegisterScreen;
lv_obj_t * ui_RegisterScreenLabel;
lv_obj_t * ui_RegisterScreenNameInputArea;
void ui_event_RegisterScreenKeyboard(lv_event_t * e);
lv_obj_t * ui_RegisterScreenKeyboard;
void ui_event_RegisterScreenCancelButton(lv_event_t * e);
lv_obj_t * ui_RegisterScreenCancelButton;
lv_obj_t * ui_RegisterScreenCancelButtonLabel;
// CUSTOM VARIABLES

// SCREEN: ui_MoneyDelegateScreen
void ui_MoneyDelegateScreen_screen_init(void);
lv_obj_t * ui_MoneyDelegateScreen;
lv_obj_t * ui_MoneyDelegateScreenHeaderLabel;
lv_obj_t * ui_MoneyDelegateScreenTextArea;
lv_obj_t * ui_MoneyDelegateScreenKeyboard;
lv_obj_t * ui_MoneyDelegateScreenCancelButton;
lv_obj_t * ui_MoneyDelegateScreenCancelButtonLabel;
// CUSTOM VARIABLES

// SCREEN: ui_SuccessScreen
void ui_SuccessScreen_screen_init(void);
lv_obj_t * ui_SuccessScreen;
lv_obj_t * ui_Label4;
void ui_event_SuccessScreenButton(lv_event_t * e);
lv_obj_t * ui_SuccessScreenButton;
lv_obj_t * ui_SuccessScreenButtonLabel;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
TaskHandle_t nfcTask = NULL;

void ui_event_HomePageBeginButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LogInChoose, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_LogInChoose_screen_init);
        xTaskCreate(read_nfc_card, "nfccardreader", (4 * 1024), NULL, 1, &nfcTask);
    }
}

void ui_event_MainScreenLogoutButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomePage_screen_init);
    }
}

void ui_event_LogInScreenCancelButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomePage_screen_init);
    }
}

void ui_event_RegisterScreenKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        onRegisterKeyboardEnterPressed(e);
    }
}

void ui_event_RegisterScreenCancelButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomePage_screen_init);
    }
}

void ui_event_SuccessScreenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_MainScreenInvestButton(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if(event_code == LV_EVENT_CLICKED) {
		isInvest = true;
        isDeposit = false;
		isWithdraw = false;
		lv_label_set_text(ui_MoneyDelegateScreenHeaderLabel, "Enter amount to invest");
        _ui_screen_change(&ui_MoneyDelegateScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MoneyDelegateScreen_screen_init);
    }
}

void ui_event_MainScreenDepositButton(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if(event_code == LV_EVENT_CLICKED) {
		isInvest = false;
        isDeposit = true;
		isWithdraw = false;
		lv_label_set_text(ui_MoneyDelegateScreenHeaderLabel, "Enter amount to deposit");
        _ui_screen_change(&ui_MoneyDelegateScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MoneyDelegateScreen_screen_init);
    }
}

void ui_event_MainScreenWithdrawButton(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	if(event_code == LV_EVENT_CLICKED) {
		isInvest = false;
        isDeposit = false;
		isWithdraw = true;
		lv_label_set_text(ui_MoneyDelegateScreenHeaderLabel, "Enter amount to withdraw");
        _ui_screen_change(&ui_MoneyDelegateScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MoneyDelegateScreen_screen_init);
    }
}

void ui_event_MoneyDelegateScreenCancelButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomePage_screen_init();
    ui_MainScreen_screen_init();
    ui_LogInChoose_screen_init();
    ui_RegisterScreen_screen_init();
    ui_MoneyDelegateScreen_screen_init();
    ui_SuccessScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    http_get_BTC_price();
    //http_get_user_orders();
    lv_disp_load_scr(ui_HomePage);
    
   // lv_disp_load_scr(ui_MainScreen);
}
