// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: InvestiGO

#include <stdio.h>
#include "ui.h"
#include "database.h"

void onRegisterKeyboardEnterPressed(lv_event_t * e)
{
	http_register_user();
}
